---
title: "CBADA Quarto Templates Extension"
format:
  html:
    toc: false
---

# CCDM Extension For Quarto Presentations

The `CCDMQuarto` Quarto extension provides official Analytics for the Australian Grains Industry (CCDM) project theming for Quarto revealjs presentations.

See the included template and demo file for each format here: - **CCDM revealjs Presentation:** [CCDM revealjs Slide Demo](https://cbada-aus.github.io/CCDMQuarto/demos/template-revealjs.html#/title-slide) ([Source](https://github.com/CCDM-AUS/CCDMQuarto/blob/main/docs/demos/template-revealjs.qmd)) (this is an `CCDMQuarto` exclusive)

## Installing

### Getting Quarto

If you do not have Quarto installed on your device (and are not already using RStudio, which includes it by default), you will need to do that first.
[Go here](https://quarto.org/docs/get-started/) for instructions on how to install Quarto.

### Getting the Template

Use your terminal or command prompt to run the install commands.
Alternatively, if you use RStudio or VS Code(ium)/Positron you can use the terminal emulator, but not the R/Python/Julia REPL (read-eval-print-loop console), in those integrated development environments (IDE) to run the commands.
Or, if you prefer and you are using Windows, you may need to install the Windows Subsystem for Linux (WSL) to use the `bash` command.
For more information, see [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/wsl/install).

You can obtain a copy of the extension by using the following commands in your Bash terminal (CLI):

```bash
cd your_quarto_project_folder
quarto use template CCDM-CBADA/CBADAQuarto
```

This will install the extension and create an example qmd file that you can use as a starting place for your LaTeX PDF, MS Word .docx or reveal.js presentation slides.

## Using

For documentation on using reveal.js slides in Quarto, please see, <https://quarto.org/docs/presentations/revealjs/>.

To use the formatted output, save your qmd file into the extension folder that you created using the command above.
Then, in the output format use:

- `cbada-revealjs`, for a revealjs presentation

### Template

If you use the Bash command above to install the extension and create a sub directory following the command prompt, there will be a .qmd file created using the name that you input for the sub directory.

## Updating

As we continue to improve this extension through bug fixes or adding new functionality, you can update it easily like so:

```bash
cd your_quarto_project_folder
quarto update CCDM-CBADA/CBADAQuarto
```

## Logo Rights

The logos of this project do not come under MIT License.
The Centre for Crop and Disease Management, Curtin University and the Grains Research and Development Corporation retain full rights to all logos.
